### PR TITLE
travis ci and codecov setup

### LINKED ISSUE #32: Production Continuous Integration

### PR DESCRIPTION
**Pull request by iaptsiauri**
closes #32

### CODE REVIEW

**Comment by fishera123** [comment]
great 👍

**Comment by yaryribero** [comment]
Hi Ilia, can you write some instructions how to test this ticket?

**Comment by fishera123** [comment]
@yaryribero we have added travis-ci service in dagcoin repository which monitors pull request updates. if someone creates or updates pull request travis-ci will trigger build and run instructions provided from travis.yml after it finishes running tests it calls codecov which will generate report against testnet.

**Comment by fishera123** [comment]
@yaryribero  until this pr is not merged all other pr will fail because in testnet we have legacy travis config file and ci is executing that one.

**Comment by fishera123** [comment]
@iaptsiauri please put style lint check before running karma tests

**Comment by iaptsiauri** [comment]
@fishera123 style linting has been added only for the *.sccs files

**Comment by fishera123** [comment]
Great

**Pull request merged**
